### ISSUE TITLE
Error initializing a spatial frequency tuning calc document

### ISSUE THREAD

**Issue by aviL221** [VH-Lab/NDIcalc-vis-matlab#24]
`ndi.document('/Users/vhlab/Documents/MATLAB/tools/NDIcalc-vis-matlab/ndi_common/database_documents/calc/spatial_frequency_tuning_calc.json')` produces the error: 
```matlab
Error using jsondecode
JSON syntax error at line 48, column 23 (character 1181): expected ',' or ']' but found '0'.

Error in ndi.document.readblankdefinition (line 753)
				j = jsondecode(t);

Error in ndi.document.readblankdefinition (line 764)
							s_super{end+1} = ndi.document.readblankdefinition(item.definition);

Error in ndi.document (line 28)
					document_properties = ndi.document.readblankdefinition(document_type);
``` 
Whereas `ndi.document('/Users/vhlab/Documents/MATLAB/tools/NDIcalc-vis-matlab/ndi_common/database_documents/calc/temporal_frequency_tuning_calc.json')` works fine.

**Comment by stevevanhooser** [comment]
This is fixed on [avicalctesting3](https://github.com/VH-Lab/NDIcalc-vis-matlab/tree/avicalctesting3).

**Comment by stevevanhooser** [comment]
(you can pull to update)
