### ISSUE TITLE
Error while running the spatial_freq_tuning_calc.test method

### ISSUE THREAD

**Issue by aviL221** [VH-Lab/NDIcalc-vis-matlab#28]
I ran the following test on the spatial frequency tuning calculator: `[b,errormsg,b_expected,doc_output,doc_expected_output] = spatial_freq_tuning_calc.test('standard',2,1);`
I got an error that read

> Unrecognized function or variable 'search_options'.
> Error in vis.frequency.spatial_frequency_analysis (line 88)
> 	dog_par=fminsearch('dog_error',[r0 re se ri si],search_options,...

Not sure what value 'search_options' should hold here. Somehow it wasn't initiated in my latest version of vis.frequency.spatial_frequency_analysis.

**Comment by stevevanhooser** [comment]
I made an update to ndi2beta_june14 that fixes this. If you push your latest to your branch we can do a pull request/merge.
