### ISSUE TITLE
Mismatch between polymorphic functions vis.contrast.indexes.c50interpolated in NDIcalc-vis-matlab and vlt.neuro.vision.contrast.indexes.c50interpolated in vhlab-toolbox-matlab

### ISSUE THREAD

**Issue by aviL221** [VH-Lab/NDIcalc-vis-matlab#41]
Change in line 46 of vis.contrast.indexes.c50interpolated in NDIcalc-vis-matlab, adapted from vis.contrast.indexes.contrastfit2c50 in NDIcalc-vis-matlab, to return the **first** half-maximum contrast. This change should be adopted in vlt.neuro.vision.contrast.indexes.c50interpolated in vhlab-toolbox-matlab as well.

**Comment by stevevanhooser** [comment]
Fixed in vhlab-toolbox-matlab
